// AskMe Frontend Central API Configuration
export const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL || 'http://localhost:5000/api';
export const SOCKET_URL = process.env.NEXT_PUBLIC_SOCKET_URL || 'http://localhost:5000';

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: `${API_BASE_URL}/adminauth/login`,
    REGISTER: `${API_BASE_URL}/adminauth/register`,
    CREATOR_REGISTER: `${API_BASE_URL}/auth/creator/register`,
    LOGOUT: `${API_BASE_URL}/auth/logout`,
    ME: `${API_BASE_URL}/auth/me`,
  },
  CREATORS: {
    REGISTER: `${API_BASE_URL}/creators/register`,
    LOGIN: `${API_BASE_URL}/creators/login`,
    LIST: `${API_BASE_URL}/admin/creators`,
    SUBMIT_KYC: `${API_BASE_URL}/creators/kyc`,
    KYC_STATUS: `${API_BASE_URL}/creators/kyc/status`,
    PROFILE: `${API_BASE_URL}/creators/profile`,
    LIVE_SESSIONS: `${API_BASE_URL}/creators/live-sessions`,
    PAY_SESSION: `${API_BASE_URL}/creators/pay/session`,
    PAY_PROCESS: `${API_BASE_URL}/creators/pay/process`,
    OVERLAY_DATA: `${API_BASE_URL}/creators/overlay/data`,
    OVERLAY_ALERTS: `${API_BASE_URL}/creators/overlay/alerts`,
    WALLET_DETAILS: `${API_BASE_URL}/creators/wallet/details`,
    WALLET_WITHDRAW: `${API_BASE_URL}/creators/wallet/withdraw`,
    WALLET_WITHDRAWALS: `${API_BASE_URL}/creators/wallet/withdrawals`,
    BANK_ACCOUNT: `${API_BASE_URL}/creators/bank-account`,
    CHAT_MESSAGES: `${API_BASE_URL}/creators/live-sessions`,
    CHAT_REPLY: `${API_BASE_URL}/creators/live-sessions/chat/reply`,
    NOTIFICATIONS: `${API_BASE_URL}/creators/notifications`,
    DONATION_STATUS: `${API_BASE_URL}/creators/donations`,
    VERIFY_UPI: `${API_BASE_URL}/creators/verify-upi`,
  },
  ADMIN: {
    DASHBOARD: `${API_BASE_URL}/admin/dashboard`,
    CREATORS: `${API_BASE_URL}/admin/creators`,
    KYC: `${API_BASE_URL}/admin/kyc`,
    LIVE_SESSIONS: `${API_BASE_URL}/admin/live-sessions`,
    PAYMENTS: `${API_BASE_URL}/admin/payments`,
    WALLETS: `${API_BASE_URL}/admin/wallets`,
    WITHDRAWALS: `${API_BASE_URL}/admin/withdrawals`,
    COMMISSION: `${API_BASE_URL}/admin/commission`,
    REPORTS: `${API_BASE_URL}/admin/reports`,
    NOTIFICATIONS: `${API_BASE_URL}/admin/notifications`,
    OPERATIONS: `${API_BASE_URL}/admin/operations`,
    MEMBERSHIPS_OVERVIEW: `${API_BASE_URL}/admin/memberships/overview`,
    MEMBERSHIPS_PLANS: `${API_BASE_URL}/admin/memberships/plans`,
    MEMBERSHIPS_SUBSCRIPTIONS: `${API_BASE_URL}/admin/memberships/subscriptions`,
    MEMBERSHIPS_CREATORS: `${API_BASE_URL}/admin/memberships/creators`,
    MEMBERSHIPS_ASSIGN: `${API_BASE_URL}/admin/memberships/assign`,
  },
  VIEWERS: {
    REGISTER: `${API_BASE_URL}/viewers/register`,
    LOGIN: `${API_BASE_URL}/viewers/login`,
    PROFILE: `${API_BASE_URL}/viewers/profile`,
    PUBLIC_LIVE_FEED: `${API_BASE_URL}/viewers/public/live-feed`,
    PUBLIC_CREATOR_PROFILE: `${API_BASE_URL}/viewers/public/creators`,
    FOLLOW: `${API_BASE_URL}/viewers/follow`,
    FOLLOWING: `${API_BASE_URL}/viewers/following`,
    VIP_SUBSCRIBE: `${API_BASE_URL}/viewers/vip/subscribe`,
    VIP_MY_MEMBERSHIPS: `${API_BASE_URL}/viewers/vip/my-memberships`,
    VIP_CANCEL: `${API_BASE_URL}/viewers/vip/cancel`,
    VIP_PLANS: `${API_BASE_URL}/viewers/vip/plans`,
    MY_QUESTIONS: `${API_BASE_URL}/viewers/my-questions`,
    PUBLIC_PAST_STREAMS: `${API_BASE_URL}/viewers/public/past-streams`,
  },
  KYC: `${API_BASE_URL}/admin/kyc`,
  PAYOUTS: `${API_BASE_URL}/admin/withdrawals`,
};
